---
- include_tasks: apt.yaml
  when:
    - ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
- include_tasks: install_prerequisites_ansible.yaml
  when:
    - ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
- include_tasks: rhel_register.yaml
  when:
   - ansible_distribution == "Red Hat Enterprise Linux"
- include_tasks: win_install_chocolatey.yaml
  when:
   - ansible_os_family == "Windows"
# - include_tasks: win_enable_sshserver.yaml
#   when:
#    - ansible_os_family == "Windows"
