---
- name: get secrets with ssm paramter store
  set_fact:
    initpass:
      secret: "{{ lookup('aws_ssm', '/Password/agent_sa') }}"

- name: 'output secrets'
  debug: var="{{ item }}"
  with_items:
    - "initpass.secret"
    - "initpass.not_exist"
    
- name: Create a group arcgis
  group:
    name: "{{ arcgis_service_account_group }}"
    state: present

- name: Create an arcgis user
  user:
    name: "{{ arcgis_service_account }}"
    password: "{{ initpass.secret }}"
    state: present
    group: "{{ arcgis_service_account_group }}"